[package]
name = "nmsr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
rayon = "1.5.3"

#[profile.release]
#lto = true

[[bin]]
name = "nmsr"
path = "src/main.rs"