[workspace]

members = [
    "nmsr-lib",
    "nmsr-jni",
    "nmsr-aas",
    "nmsr-multi-parts-organizer",
    "nmsr-backfaces-optimizer"
]

[profile.dev.package.nmsr-lib]
opt-level = 3
[profile.dev.package.image]
opt-level = 3
