[workspace]

members = [
    "nmsr-lib",
    #"nmsr-jni",
    "nmsr-aas",
    "utils/nmsr-multi-parts-organizer",
    "utils/nmsr-backfaces-optimizer",
]

[profile.dev.package.image]
opt-level = 3
[profile.release]
debug = true