[workspace]

members = [
    "nmsr-lib",
    #"nmsr-jni",
    "nmsr-aas",
    "utils/nmsr-multi-parts-organizer",
    "utils/nmsr-backfaces-optimizer",
    "nmsr-3d-renderer/nmsr-player-parts",
    "nmsr-3d-renderer/nmsr-rendering",
    "nmsr-3d-renderer/nmsr-wgpu-windowed",
]

[profile.dev.package.image]
opt-level = 3