[workspace]
resolver = "2"

package.authors = [
    "NickAcPT"
]

package.homepage = "https://github.com/NickAcPT/nmsr-rs"

members = [
    "nmsr-lib",
    #"nmsr-jni",
    "nmsr-aas",
    "utils/nmsr-rendering-palette-extractor",
    "utils/nmsr-multi-parts-organizer",
    "utils/nmsr-backfaces-optimizer",
    "nmsr-3d-renderer/nmsr-player-parts",
    "nmsr-3d-renderer/nmsr-rendering",
    "nmsr-3d-renderer/nmsr-wgpu-windowed",
]

[profile.dev.package.image]
opt-level = 3

[patch.crates-io]
smaa = { git = "https://github.com/NickAcPT/smaa-rs", branch = "nmsr" }