# Server configuration.
[server]
# The address to bind the server to.
address = "0.0.0.0"
# The port to bind the server to.
port = 8080


# Tracing configuration.
[tracing]
# The OpenTelemetry endpoint to send traces to.
endpoint = "http://127.0.0.1:4317"
# The service name to use for traces. (Optional, defaults to "nmsr-aas")
service_name = "nmsr-aas"


[caching]
# The interval of time to run the cleanup task.
# This task will remove any files in the cache that are older than the image cache expiry.
# This task will run on startup, and then every time the interval has passed.
cleanup_interval = "1h"

# How long it takes to expire the cache of the resolved models
# This cache is used to prevent the same uuid from being resolved multiple times in a short period of time.
# Setting this to a big value will reduce the amount of requests to the Mojang API, but will increase the time
# it takes to update the skin for a player.
# This value is also used for the Cache-Control header age for the skin requests.
resolve_cache_duration = "15m"

# How long it takes to expire the cache of the rendered models.
# Setting this to a big value will reduce the amount of renders that need to be done, but will increase the time
# it takes to update the skin for a player.
# This value is also used for the Cache-Control header age for the render requests.
render_cache_duration = "15m"

# Cache biases for specific entries.
# A cache bias is a duration of time to keep a specific entry in the cache.
# This is useful for entries that are requested often, such as the models in the home page.
# Examples:
#
# [cache_biases]
# # Cache NickAc's skin for 2h:
# ad4569f3-7576-4376-a7c7-8e8cfcd9b832 = "2h"
#
# # Cache one of Koide's skins indefinitely:
# 7c7e2befcd4bb8af1c970ec80d585a76bfb23d62c4c82126cd86548beaa695f7 = "CacheIndefinitely"
[caching.cache_biases]


[mojank]
# The URL to the Mojang API's session server.
# This can be useful if you want to use a caching proxy for the Mojang API and is used to
# get the game profile for a player based on their uuid.
session_server = "https://sessionserver.mojang.com"
# The URL to the Mojang API's textures server.
textures_server = "https://textures.minecraft.net"
# The rate limit to use for requests to the session server in a 1 second window.
session_server_rate_limit = 10