[package]
name = "nmsr-rasterizer-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0"
nmsr-rendering = { version = "0.1.0", path = "../nmsr-rs/nmsr-3d-renderer/nmsr-rendering" }
image = { version = "0", default-features = false, features = ["png"] }