[package]
name = "nmsr-parts"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17.0"
bytemuck = { version = "1.13.1", features = ["derive"] }
glam = { version = "0.24.1", features = ["bytemuck"] }
