[package]
name = "nmsr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nmsr-lib = { path = "../nmsr-lib" }
image = "0.24.4"
anyhow = "1.0.66"