[package]
name = "nmsr-rendering-palette-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
heck = "0.4.1"
image = { workspace = true, default-features = false, features = ["png"] }

