[build]
rustflags = ["-Z", "threads=8", "-Ctarget-feature=+simd128,+relaxed-simd"]

target = "wasm32-unknown-unknown"

[unstable]
build-std = ["panic_abort", "std"]
build-std-features = ["panic_immediate_abort"]