[package]
name = "nmsr-rendering-blockbench-model-generator-experiment"
version = "0.1.0"
edition = "2021"
authors.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
image = { version = "0.24.7", default-features = false, features = ["png"] }
itertools = "0.11.0"
nmsr-rendering = { version = "0.1.0", path = "../../nmsr-3d-renderer/nmsr-rendering" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
derive_more = { version = "1.0.0-beta.3", features = ["deref", "debug"] }
ears-rs = { git = "https://github.com/NickAcPT/ears-rs" }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
glam = { version = "0.24.1", features = ["serde"] }
base64 = "0.21.4"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }

[features]
default = ["nmsr-rendering/part_tracker"]
ears = ["nmsr-rendering/ears"]
