[package]
name = "nmsr-lib"
version = "0.2.2"
edition = "2021"
authors = ["NickAcPT"]

[dependencies]
image = { version = "0.24.5", features = ["png"], default-features = false }
thiserror = "1.0.37"
ears-rs = { git = "https://github.com/NickAcPT/ears-rs" }
rayon = { version = "1.6.0", optional = true }
vfs = { version = "0.7.1" }
serde = { version = "1.0.147", features = ["derive"], optional = true }
either = "1.8.0"
tracing = { version = "0.1.37", optional = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
parallel_iters = ["dep:rayon"]
serializable_parts = ["dep:serde"]
ears = []
tracing = ["dep:tracing"]