[package]
name = "nmsr-lib"
version = "0.1.0"
edition = "2021"
authors = ["NickAcPT"]

[dependencies]
image = { version = "0.24.4", features = ["png"], default-features = false }
thiserror = "1.0.37"
ears-rs = { git = "https://github.com/NickAcPT/ears-rs" }

[lib]
crate-type = ["cdylib", "rlib"]