[package]
name = "nmsr-jni"
version = "0.1.0"
edition = "2021"
authors = ["NickAcPT"]

[dependencies]
nmsr-lib = { path = "../nmsr-lib" }
jni = "0.20.0"
image = { version = "0.24.4", features = ["png"], default-features = false }

[lib]
crate_type = ["cdylib"]