[package]
name = "nmsr-jni"
version = "0.1.0"
edition = "2021"

authors.workspace = true
homepage.workspace = true

[dependencies]
nmsr-lib = { path = "../nmsr-lib" }
jni = "0.21.1"
image = { version = "0.24.6", features = ["png"], default-features = false }

[lib]
crate_type = ["cdylib"]