name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Ensure rustfmt is installed and setup problem matcher
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Build
      run: cargo build --bin=nmsr-aas --package=nmsr-aas --verbose
      
    - name: Build (ears features)
      run: cargo build --bin=nmsr-aas --package=nmsr-aas --features=ears --verbose
      
    - name: Run tests
      run: cargo test --verbose
