name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    # Ensure rustfmt is installed and setup problem matcher
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: ""
    
    - name: Build
      run: cargo build --bin=nmsr-aas --package=nmsr-aas --verbose
      
    - name: Build (ears features)
      run: cargo build --bin=nmsr-aas --package=nmsr-aas --features=ears --verbose
      
    - name: Run tests
      run: cargo test --verbose

  docker_build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        push: false
        context: .